In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from wordcloud import WordCloud
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import r2_score
df = pd.read_csv("spotify.csv")
df.head()

title      artist the genre of the track  year  \
0      Hey, Soul Sister       Train             neo mellow  2010   
1  Love The Way You Lie      Eminem        detroit hip hop  2010   
2               TiK ToK       Kesha              dance pop  2010   
3           Bad Romance   Lady Gaga              dance pop  2010   
4  Just the Way You Are  Bruno Mars                    pop  2010   

   Beats.Per.Minute -The tempo of the song  \
0                                       97   
1                                       87   
2                                      120   
3                                      119   
4                                      109   

   Energy- The energy of a song - the higher the value, the more energtic  \
0                                                 89                        
1                                                 93                        
2                                                 84                        
3                                                 92                        
4                                                 84                        

   Danceability - The higher the value, the easier it is to dance to this song  \
0                                                 67                             
1                                                 75                             
2                                                 76                             
3                                                 70                             
4                                                 64                             

   Loudness/dB - The higher the value, the louder the song  \
0                                                 -4         
1                                                 -5         
2                                                 -3         
3                                                 -4         
4                                                 -5         

   Liveness - The higher the value, the more likely the song is a live recording  \
0                                                  8                               
1                                                 52                               
2                                                 29                               
3                                                  8                               
4                                                  9                               

   Valence - The higher the value, the more positive mood for the song  \
0                                                 80                     
1                                                 64                     
2                                                 71                     
3                                                 71                     
4                                                 43                     

   Length - The duration of the song  \
0                                217   
1                                263   
2                                200   
3                                295   
4                                221   

   Acousticness - The higher the value the more acoustic the song is  \
0                                                 19                   
1                                                 24                   
2                                                 10                   
3                                                  0                   
4                                                  2                   

   Speechiness - The higher the value the more spoken word the song contains  \
0                                                  4                           
1                                                 23                           
2                                                 14                           
3                                                  4       

PreProcessing

In [54]:
df.isna()

title  artist  the genre of the track   year  \
0    False   False                   False  False   
1    False   False                   False  False   
2    False   False                   False  False   
3    False   False                   False  False   
4    False   False                   False  False   
..     ...     ...                     ...    ...   
598  False   False                   False  False   
599  False   False                   False  False   
600  False   False                   False  False   
601  False   False                   False  False   
602  False   False                   False  False   

     Beats.Per.Minute -The tempo of the song  \
0                                      False   
1                                      False   
2                                      False   
3                                      False   
4                                      False   
..                                       ...   
598                                    False   
599                                    False   
600                                    False   
601                                    False   
602                                    False   

     Energy- The energy of a song - the higher the value, the more energtic  \
0                                                False                        
1                                                False                        
2                                                False                        
3                                                False                        
4                                                False                        
..                                                 ...                        
598                                              False                        
599                                              False                        
600                                              False                        
601                                              False                        
602                                              False                        

     Danceability - The higher the value, the easier it is to dance to this song  \
0                                                False                             
1                                                False                             
2                                                False                             
3                                                False                             
4                                                False                             
..                                                 ...                             
598                                              False                             
599                                              False                             
600                                              False                             
601                                              False                             
602                                              False                             

     Loudness/dB - The higher the value, the louder the song  \
0                                                False         
1                                                False         
2                                                False         
3                                                False         
4                                                False         
..                                                 ...         
598                                              False         
599                                              False         
600                                              False         
601                                              False         
602                                              False         

     Liveness - The higher the value, the more likely the song i

In [55]:
df.dtypes

title                                                                            object
artist                                                                           object
the genre of the track                                                           object
year                                                                              int64
Beats.Per.Minute -The tempo of the song                                           int64
Energy- The energy of a song - the higher the value, the more energtic            int64
Danceability - The higher the value, the easier it is to dance to this song       int64
Loudness/dB - The higher the value, the louder the song                           int64
Liveness - The higher the value, the more likely the song is a live recording     int64
Valence - The higher the value, the more positive mood for the song               int64
Length - The duration of the song                                                 int64
Acousticness - The higher the va

Renaming columns

In [56]:
df.rename(columns = {
    'the genre of the track': 'genre',
    'Beats.Per.Minute -The tempo of the song': 'BPM',
    'Energy- The energy of a song - the higher the value, the more energtic': 'Energy',
    'Danceability - The higher the value, the easier it is to dance to this song': 'Danceability',
    'Loudness/dB - The higher the value, the louder the song': 'Loudness',
    'Liveness - The higher the value, the more likely the song is a live recording': 'Liveness',
    'Valence - The higher the value, the more positive mood for the song': 'Valence',
    'Length - The duration of the song': 'Length',
    'Acousticness - The higher the value the more acoustic the song is': 'Acousticness',
    'Speechiness - The higher the value the more spoken word the song contains': 'Speechiness',
    'Popularity- The higher the value the more popular the song is': 'Popularity'
}, inplace=True)

In [57]:
df.dtypes

title           object
artist          object
genre           object
year             int64
BPM              int64
Energy           int64
Danceability     int64
Loudness         int64
Liveness         int64
Valence          int64
Length           int64
Acousticness     int64
Speechiness      int64
Popularity       int64
dtype: object

### Analysis of numeric features

In [58]:
df1 = df[df['Popularity'] > 75]
df1

title            artist  \
0                                   Hey, Soul Sister             Train   
1                               Love The Way You Lie            Eminem   
2                                            TiK ToK             Kesha   
3                                        Bad Romance         Lady Gaga   
4                               Just the Way You Are        Bruno Mars   
..                                               ...               ...   
593                                    Call You Mine  The Chainsmokers   
594                        No Guidance (feat. Drake)       Chris Brown   
595                   Antisocial (with Travis Scott)        Ed Sheeran   
596  Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)          DJ Snake   
597                                Con Calma - Remix      Daddy Yankee   

               genre  year  BPM  Energy  Danceability  Loudness  Liveness  \
0         neo mellow  2010   97      89            67        -4         8   
1    detroit hip hop  2010   87      93            75        -5        52   
2          dance pop  2010  120      84            76        -3        29   
3          dance pop  2010  119      92            70        -4         8   
4                pop  2010  109      84            64        -5         9   
..               ...   ...  ...     ...           ...       ...       ...   
593       electropop  2019  104      70            59        -6        34   
594        dance pop  2019   93      45            70        -7        16   
595              pop  2019  152      82            72        -5        36   
596  electronic trap  2019   96      80            84        -4         6   
597            latin  2019   94      87            74        -3         4   

     Valence  Length  Acousticness  Speechiness  Popularity  
0         80     217            19            4          83  
1         64     263            24           23          82  
2         71     200            10           14          80  
3         71     295             0            4          79  
4         43     221             2            4          78  
..       ...     ...           ...          ...         ...  
593       52     218            20            3          81  
594       14     261            12           15          81  
595       91     162            13            5          78  
596       62     213            16           23          77  
597       61     181            17            5          76  

[171 rows x 14 columns]

In [59]:
df["Popularity"] = pd.cut(x=df['Popularity'], bins = [-1, 50, 75, 99], labels =[0, 1, 2])
df.head(10)

title         artist            genre  \
0                            Hey, Soul Sister          Train       neo mellow   
1                        Love The Way You Lie         Eminem  detroit hip hop   
2                                     TiK ToK          Kesha        dance pop   
3                                 Bad Romance      Lady Gaga        dance pop   
4                        Just the Way You Are     Bruno Mars              pop   
5                                        Baby  Justin Bieber     canadian pop   
6                                    Dynamite      Taio Cruz        dance pop   
7                                     Secrets    OneRepublic        dance pop   
8  Empire State of Mind (Part II) Broken Down    Alicia Keys          hip pop   
9                    Only Girl (In The World)        Rihanna    barbadian pop   

   year  BPM  Energy  Danceability  Loudness  Liveness  Valence  Length  \
0  2010   97      89            67        -4         8       80     217   
1  2010   87      93            75        -5        52       64     263   
2  2010  120      84            76        -3        29       71     200   
3  2010  119      92            70        -4         8       71     295   
4  2010  109      84            64        -5         9       43     221   
5  2010   65      86            73        -5        11       54     214   
6  2010  120      78            75        -4         4       82     203   
7  2010  148      76            52        -6        12       38     225   
8  2010   93      37            48        -8        12       14     216   
9  2010  126      72            79        -4         7       61     235   

   Acousticness  Speechiness Popularity  
0            19            4          2  
1            24           23          2  
2            10           14          2  
3             0            4          2  
4             2            4          2  
5             4           14          2  
6             0            9          2  
7             7            4          2  
8            74            3          2  
9            13            4          1

In [60]:
df['Popularity'].value_counts()

1    362
2    171
0     70
Name: Popularity, dtype: int64

PCA


*   only considering the numerical columns
* classifiers tried: Random forest, Decision tree, NB, SVM, Logistic Regression



In [61]:
df_popular = df[df['Popularity']==2]
df_popular.head()

title      artist            genre  year  BPM  Energy  \
0      Hey, Soul Sister       Train       neo mellow  2010   97      89   
1  Love The Way You Lie      Eminem  detroit hip hop  2010   87      93   
2               TiK ToK       Kesha        dance pop  2010  120      84   
3           Bad Romance   Lady Gaga        dance pop  2010  119      92   
4  Just the Way You Are  Bruno Mars              pop  2010  109      84   

   Danceability  Loudness  Liveness  Valence  Length  Acousticness  \
0            67        -4         8       80     217            19   
1            75        -5        52       64     263            24   
2            76        -3        29       71     200            10   
3            70        -4         8       71     295             0   
4            64        -5         9       43     221             2   

   Speechiness Popularity  
0            4          2  
1           23          2  
2           14          2  
3            4          2  
4            4          2

In [62]:
X = df.iloc[:,:13].values
y = df.iloc[:,13].values
X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                   random_state=104, 
                                   test_size=0.25, 
                                   shuffle=True,
                                   stratify=y)

In [63]:
print(X_train[:,3:13])

[[2014 120 35 ... 239 28 3]
 [2017 100 67 ... 264 58 6]
 [2015 123 89 ... 189 2 3]
 ...
 [2015 100 76 ... 264 25 5]
 [2012 128 84 ... 228 0 6]
 [2015 89 59 ... 309 20 5]]


without year column

In [64]:
# X1=df_popular.iloc[:,:3].values
# X = df_popular.iloc[:,3:13].values
# y = df_popular.iloc[:,13].values
X1 = X_train[:,:4]

In [65]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train[:,4:13])
X_test = scaler.transform(X_test[:,4:13])

In [66]:
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
accuracies_pca = []
n_components = [1,2,3,4,5,6,7,8,9]
max_accuracy = float('-inf')

X = df.iloc[:,:13].values
y = df.iloc[:,13].values
X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                  random_state=104, 
                                  test_size=0.25, 
                                  shuffle=True,
                                  stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train[:,4:13])
X_test = scaler.transform(X_test[:,4:13])
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print("Explained variance for each principal component:",explained_variance)
classifier = RandomForestClassifier(max_depth=5, random_state=0)
classifier.fit(X_train, Y_train)
# Predicting the Test set results
y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, y_pred)
print("PCA with random forest classifier\nn=",2)
print(cm)
accuracy = accuracy_score(Y_test, y_pred)
max_accuracy = max(accuracy,max_accuracy)
print('Accuracy:',accuracy)
accuracies_pca.append(max_accuracy)

Explained variance for each principal component: [0.27152115 0.16085569]
PCA with random forest classifier
n= 2
[[ 0 16  1]
 [ 0 85  6]
 [ 0 32 11]]
Accuracy: 0.6357615894039735


In [67]:
from sklearn.tree import DecisionTreeClassifier
max_accuracy = float('-inf')

X = df.iloc[:,:13].values
y = df.iloc[:,13].values
X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                  random_state=104, 
                                  test_size=0.25, 
                                  shuffle=True,
                                  stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train[:,4:13])
X_test = scaler.transform(X_test[:,4:13])
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print("Explained variance for each principal component:",explained_variance)
classifier = DecisionTreeClassifier(max_depth=5, random_state=0)
classifier.fit(X_train, Y_train)
# Predicting the Test set results
y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, y_pred)
print("PCA with decision tree classifier\nn=",2)
print(cm)
accuracy = accuracy_score(Y_test, y_pred)
max_accuracy = max(accuracy,max_accuracy)
print('Accuracy:',accuracy)
accuracies_pca.append(max_accuracy)

Explained variance for each principal component: [0.27152115 0.16085569]
PCA with decision tree classifier
n= 2
[[ 0 12  5]
 [ 1 79 11]
 [ 0 33 10]]
Accuracy: 0.5894039735099338


In [68]:
from sklearn.naive_bayes import GaussianNB
max_accuracy = float('-inf')

X = df.iloc[:,:13].values
y = df.iloc[:,13].values
X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                  random_state=104, 
                                  test_size=0.25, 
                                  shuffle=True,
                                  stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train[:,4:13])
X_test = scaler.transform(X_test[:,4:13])
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print("Explained variance for each principal component:",explained_variance)
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
# Predicting the Test set results
y_pred = gnb.predict(X_test)
cm = confusion_matrix(Y_test, y_pred)
print("PCA with naive bayes classifier\nn=",2)
print(cm)
accuracy = accuracy_score(Y_test, y_pred)
max_accuracy = max(accuracy,max_accuracy)
print('Accuracy:',accuracy)
accuracies_pca.append(max_accuracy)

Explained variance for each principal component: [0.27152115 0.16085569]
PCA with naive bayes classifier
n= 2
[[ 4 12  1]
 [ 5 82  4]
 [ 1 38  4]]
Accuracy: 0.5960264900662252


In [69]:
from sklearn.svm import SVC

max_accuracy = float('-inf')

X = df.iloc[:,:13].values
y = df.iloc[:,13].values
X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                  random_state=104, 
                                  test_size=0.25, 
                                  shuffle=True,
                                  stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train[:,4:13])
X_test = scaler.transform(X_test[:,4:13])
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print("Explained variance for each principal component:",explained_variance)
clf = SVC(kernel='linear')
clf.fit(X_train, Y_train)
# Predicting the Test set results
y_pred = clf.predict(X_test)
cm = confusion_matrix(Y_test, y_pred)
print("PCA with Support vector classifier\nn=",2)
print(cm)
accuracy = accuracy_score(Y_test, y_pred)
max_accuracy = max(accuracy,max_accuracy)
print('Accuracy:',accuracy)
accuracies_pca.append(max_accuracy)

Explained variance for each principal component: [0.27152115 0.16085569]
PCA with Support vector classifier
n= 2
[[ 0 17  0]
 [ 0 91  0]
 [ 0 43  0]]
Accuracy: 0.6026490066225165


In [70]:
from sklearn.linear_model import LogisticRegression
max_accuracy = float('-inf')
from sklearn.svm import SVC

X = df.iloc[:,:13].values
y = df.iloc[:,13].values
X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                  random_state=104, 
                                  test_size=0.25, 
                                  shuffle=True,
                                  stratify=y)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train[:,4:13])
X_test = scaler.transform(X_test[:,4:13])
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
print("Explained variance for each principal component:",explained_variance)
clf = LogisticRegression(random_state=0)
clf.fit(X_train, Y_train)
# Predicting the Test set results
y_pred = clf.predict(X_test)
cm = confusion_matrix(Y_test, y_pred)
print("PCA with Logistic Regression Classifier\nn=",2)
print(cm)
accuracy = accuracy_score(Y_test, y_pred)
max_accuracy = max(accuracy,max_accuracy)
print('Accuracy:',accuracy)
accuracies_pca.append(max_accuracy)

Explained variance for each principal component: [0.27152115 0.16085569]
PCA with Logistic Regression Classifier
n= 2
[[ 0 15  2]
 [ 0 86  5]
 [ 0 38  5]]
Accuracy: 0.6026490066225165


In [71]:
print("Maximum accuracies for PCA:",accuracies_pca)

Maximum accuracies for PCA: [0.6357615894039735, 0.5894039735099338, 0.5960264900662252, 0.6026490066225165, 0.6026490066225165]


LDA

In [72]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=2)
X_train = lda.fit_transform(X_train, Y_train)
X_test = lda.transform(X_test)

In [73]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train, Y_train)
y_pred = classifier.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(Y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(Y_test, y_pred)))

[[ 0 16  1]
 [ 0 87  4]
 [ 0 38  5]]
Accuracy0.609271523178808


LDA with random forest classifier by varying number of components


In [75]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
n_components = [1,2]
for n in n_components:
  print("n:",n)
  X = df.iloc[:,:13].values
  y = df.iloc[:,13].values
  X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                    random_state=104, 
                                    test_size=0.25, 
                                    shuffle=True,
                                    stratify=y)
  scaler = StandardScaler()
  X_train = scaler.fit_transform(X_train[:,4:13])
  X_test = scaler.transform(X_test[:,4:13])
  lda = LDA(n_components=n)
  X_train = lda.fit_transform(X_train, Y_train)
  X_test = lda.transform(X_test)
  classifier = RandomForestClassifier(max_depth=2, random_state=0)
  classifier.fit(X_train, Y_train)
  y_pred = classifier.predict(X_test)
  cm = confusion_matrix(Y_test, y_pred)
  print(cm)
  print('Accuracy' + str(accuracy_score(Y_test, y_pred)))

n: 1
[[ 0 12  5]
 [ 0 81 10]
 [ 0 33 10]]
Accuracy0.6026490066225165
n: 2
[[ 0 12  5]
 [ 0 81 10]
 [ 0 35  8]]
Accuracy0.5894039735099338


LDA with decision tree

In [76]:
n_components = [1,2]
for n in n_components:
  print("n:",n)
  X = df.iloc[:,:13].values
  y = df.iloc[:,13].values
  X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                    random_state=104, 
                                    test_size=0.25, 
                                    shuffle=True,
                                    stratify=y)
  scaler = StandardScaler()
  X_train = scaler.fit_transform(X_train[:,4:13])
  X_test = scaler.transform(X_test[:,4:13])
  lda = LDA(n_components=n)
  X_train = lda.fit_transform(X_train, Y_train)
  X_test = lda.transform(X_test)
  classifier = DecisionTreeClassifier(max_depth=5, random_state=0)
  classifier.fit(X_train, Y_train)
  # Predicting the Test set results
  y_pred = classifier.predict(X_test)
  cm = confusion_matrix(Y_test, y_pred)
  print(cm)
  print('Accuracy:',accuracy_score(Y_test, y_pred))

n: 1
[[ 0 13  4]
 [ 3 79  9]
 [ 0 34  9]]
Accuracy: 0.5827814569536424
n: 2
[[ 0 13  4]
 [ 2 79 10]
 [ 0 33 10]]
Accuracy: 0.5894039735099338


LDA with Naive Bayes Classifier

In [77]:
n_components = [1,2]
for n in n_components:
  print("n:",n)
  X = df.iloc[:,:13].values
  y = df.iloc[:,13].values
  X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                    random_state=104, 
                                    test_size=0.25, 
                                    shuffle=True,
                                    stratify=y)
  scaler = StandardScaler()
  X_train = scaler.fit_transform(X_train[:,4:13])
  X_test = scaler.transform(X_test[:,4:13])
  lda = LDA(n_components=n)
  X_train = lda.fit_transform(X_train, Y_train)
  X_test = lda.transform(X_test)
  gnb = GaussianNB()
  gnb.fit(X_train, Y_train)
  # Predicting the Test set results
  y_pred = gnb.predict(X_test)
  cm = confusion_matrix(Y_test, y_pred)
  print(cm)
  print('Accuracy:',accuracy_score(Y_test, y_pred))

n: 1
[[ 0 12  5]
 [ 0 82  9]
 [ 0 35  8]]
Accuracy: 0.5960264900662252
n: 2
[[ 0 12  5]
 [ 6 78  7]
 [ 1 35  7]]
Accuracy: 0.5629139072847682


LDA with SVC

In [78]:
n_components = [1,2]
for n in n_components:
  print("n:",n)
  X = df.iloc[:,:13].values
  y = df.iloc[:,13].values
  X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                    random_state=104, 
                                    test_size=0.25, 
                                    shuffle=True,
                                    stratify=y)
  scaler = StandardScaler()
  X_train = scaler.fit_transform(X_train[:,4:13])
  X_test = scaler.transform(X_test[:,4:13])
  lda = LDA(n_components=n)
  X_train = lda.fit_transform(X_train, Y_train)
  X_test = lda.transform(X_test)
  clf = SVC(kernel='linear')
  clf.fit(X_train, Y_train)
  # Predicting the Test set results
  y_pred = clf.predict(X_test)
  cm = confusion_matrix(Y_test, y_pred)
  print(cm)
  print('Accuracy:',accuracy_score(Y_test, y_pred))

n: 1
[[ 0 17  0]
 [ 0 91  0]
 [ 0 43  0]]
Accuracy: 0.6026490066225165
n: 2
[[ 0 17  0]
 [ 0 91  0]
 [ 0 43  0]]
Accuracy: 0.6026490066225165


LDA with logistic regression

In [79]:
n_components = [1,2]
for n in n_components:
  print("n:",n)
  X = df.iloc[:,:13].values
  y = df.iloc[:,13].values
  X_train, X_test, Y_train, Y_test = train_test_split(X,y,
                                    random_state=104, 
                                    test_size=0.25, 
                                    shuffle=True,
                                    stratify=y)
  scaler = StandardScaler()
  X_train = scaler.fit_transform(X_train[:,4:13])
  X_test = scaler.transform(X_test[:,4:13])
  lda = LDA(n_components=n)
  X_train = lda.fit_transform(X_train, Y_train)
  X_test = lda.transform(X_test)
  clf = LogisticRegression(random_state=0)
  clf.fit(X_train, Y_train)
  # Predicting the Test set results
  y_pred = clf.predict(X_test)
  cm = confusion_matrix(Y_test, y_pred)
  print(cm)
  print('Accuracy:',accuracy_score(Y_test, y_pred))

n: 1
[[ 0 14  3]
 [ 0 83  8]
 [ 0 35  8]]
Accuracy: 0.6026490066225165
n: 2
[[ 0 13  4]
 [ 1 82  8]
 [ 0 35  8]]
Accuracy: 0.5960264900662252
